name: mian_yu_zhou_server
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  dart_appwrite: ^10.0.0
  appwrite_test: ^0.3.1
  # appwrite_test:
  # path: /Users/king/Documents/appwrite_test
  darty_json_safe: ^1.0.3
  version: ^3.0.2
dev_dependencies:
  lints: ^2.0.0
